name: PR_test
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "**"
  workflow_dispatch:
  
jobs:
  read_env:
    env:
      local: ${{ vars.local }}
      supersecret: ${{ secrets.supersecret }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Read environment variable
        run: |
          #!/bin/bash
          print_secret(){
            name="$1"
            val="$2"
            local prefix=${val:0:6}
            local spaced=$(echo "$prefix" | sed 's/./& /g')
            echo " $name"
            for (( i=0; i<6; i++ )); do
                echo -n "${val:$i:1} "
            done
            echo "..."
            
          }
          print_secret local: $local
          print_secret supersecret: $supersecret
